# Generated by Django 4.0.1 on 2022-01-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visit_count',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
